# Generated by Django 2.1.7 on 2019-07-29 19:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('lemmatized', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=220, null=True)),
                ('family_name', models.CharField(blank=True, max_length=220, null=True)),
                ('nickname', models.CharField(blank=True, max_length=220, null=True)),
                ('edition', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('wiki', models.URLField(blank=True, max_length=250)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('wiki', models.URLField(blank=True, max_length=250)),
                ('gis', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_author', to='prozhito_app.Person'),
        ),
        migrations.AddField(
            model_name='entry',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='prozhito_app.Keyword', verbose_name='Text(s)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='people',
            field=models.ManyToManyField(blank=True, to='prozhito_app.Person', verbose_name='Person(s)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='places',
            field=models.ManyToManyField(blank=True, to='prozhito_app.Place', verbose_name='Text(s)'),
        ),
    ]
