# Generated by Django 2.2.4 on 2019-08-06 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=220, null=True)),
                ('family_name', models.CharField(blank=True, max_length=220, null=True)),
                ('nickname', models.CharField(blank=True, max_length=220, null=True)),
                ('edition', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('wiki', models.URLField(blank=True, max_length=1000)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=220, null=True)),
                ('from_natasha', models.BooleanField(default=False)),
                ('from_tags', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('wiki', models.URLField(blank=True, max_length=250)),
                ('gis', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('lemmatized', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('diary', models.IntegerField(default=None)),
                ('sentiment', models.CharField(blank=True, max_length=220, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_author', to='prozhito_app.Person')),
                ('keywords', models.ManyToManyField(blank=True, to='prozhito_app.Keyword', verbose_name='Keyword(s)')),
                ('people', models.ManyToManyField(blank=True, to='prozhito_app.Person', verbose_name='Person(s)')),
                ('places', models.ManyToManyField(blank=True, to='prozhito_app.Place', verbose_name='Place(s)')),
            ],
        ),
    ]
